AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'
    - '**/Gemfile'
    - '**/Guardfile'
    - 'config/**/*'
  UseCache: false
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/repositories/fakers/**/*'